spring:
  application:
    name: history-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: wallet_user
    password: wallet_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: history-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest  # Start from beginning if no offset
      enable-auto-commit: false  # Manual commit after processing
      properties:
        spring.json.trusted.packages: "*"  # Trust all packages for deserialization
    
    listener:
      ack-mode: manual  # We'll commit manually after saving to DB

server:
  port: 8081

logging:
  level:
    com.wallet: DEBUG
    org.hibernate.SQL: DEBUG

history:
  kafka:
    topic: wallet_events